public class Feb2402_Class {  
    
    public string country='Dubai'; 
    public string state;
    
    public Feb2402_Class(){

        if(country=='India'){ 
             state='Telangana' ;
        } else if(country=='USA'){ 
            state='NewJersy';
        }else if(country=='Dubai'){ 
                  state='sharja';
        }          
        
        system.debug('State=='+state);

} 
    
    public void method1(){ 
    
    
    } 
    
    public class mycls{ 
    
    
    }

}