public class Jan26class {
    public String Studentname='Sai'; 
    Public Boolean isfeepaid=true;


    Public Jan26class(){
      studentname='Uday'; 
         string studentname=studentname;
      system.debug('studentname==='+studentname);             
        
      
}
    public void method1(){
       studentname='surya';
            
        system.debug('studentname=='+studentname);  
        
        String Gender='Male';  
        system.debug('Gender=='+Gender);
   
             isfeepaid=false; 
        Boolean isfeepaid=isfeepaid; 
        system.debug('isfeepaid==='+isfeepaid);


}
}