public class Jan2701clv { 
    public String Stname='Arun';
    Public Integer Batchname=10; 
    Public Boolean isfeepaid=True;            
    public String clgname='VITS';
    
    
    Public Jan2701clv(){ 
        
        string staffname='Uday Kiran'; 
        system.debug('staffname=='+staffname); 
        
        system.debug('Batchname=='+Batchname); 
        
        system.debug('Student Name=='+Stname);       
        Stname='Kumar';
        system.debug('Student Name=='+Stname); 
        
        
        string fathername='Balchander';
        system.debug('FatherName=='+fathername); 
        fathername='Laxmirajam'; 
        system.debug('Father Name='+fathername);       
        
        
            
        system.debug('clgname=='+clgname); 
        clgname='Jyothismathi';  
        system.debug('clgname=='+clgname); 
        
        
        system.debug('clgname=='+clgname); 
        string clgname='KITS Warangal'; 
        System.debug('clgname=='+clgname);
        
    }
    
}