public class Jan2702clv {  
    Public String Name='sai';
    public String favternbame='Balachander'; 
    
   //1 Argument 
     public Jan2702clv(String SN){ 
        system.debug('Sname=='+SN); 
} 
    
    public Jan2702clv(String st,Integer Batch){

       system.debug('ST=='+st);
       system.debug('Batch='+Batch);  
        
        string fname=st; 
        system.debug('fname=='+fname);
        Integer Ba=Batch; 
        system.debug('batch=='+Ba);

} 
    
    
    Public Jan2702clv(String Name,Boolean feepaid,Integer roolnuber){  
        
       
        
        system.debug('Student Name=='+Name); 
         
                 String Myname=Name;  
        system.debug('b Name=='+Myname);
        
        system.debug('Feepaid=='+feepaid); 
        
        system.debug('Roolnumber=='+roolnuber);
                    
} 
    
    Public Jan2702clv(){
     string s2name='kiran'; 
        system.debug('s2name=='+s2name); 
        
        string str=favternbame; 
        system.debug('Father Nmae=='+favternbame);

 
}
    
}