public class Lead_Object {
//class leval Variable Declaration
Public String salutation='Ms.';
Public String firstname='G';
Public String lastname='Ragini';
Public String title;
Public String leadsource='Phone Inquiry';
Public String industry='Shipping';
Public Integer annualrevenue=58000000;
Public Integer noofemployees=100;	
Public Boolean isqualified=true;
Public String  street='Ameerpet';
Public String  city='Hyderabad';
Public String  state='TELANGANA';
Public String  zipcode='50001';
Public String  country='INDIA';
Public String productinterest='GC5000 series';
Public String siccode;	
Public Integer numberoflocations=10;
Public String phone='987654123';
Public String mobile='147523600';
Public String fax='1254025555';
Public String website;
Public String leadstatus='Open - Not Contacted';
Public String rating='Hot';
Public String email='ragini@123noemail.com';
Public String currentgenerators='JOHN';	
Public String Primary='no';
}