public class Newcal26 {
    
    public Newcal26(){
        
    }
    Public Void Addnumber(Integer a,Integer b){
        Integer sum=a+b; 
        system.debug('Addition=='+sum); 
        
} 
    public void multiplication(Integer a,Integer b){
            
            Integer Multiplication=a*b;
            system.debug('Multiplication=='+Multiplication);
        } 
    Public void new1(String studentname,Integer batch){

               string sname= studentname;   
        system.debug('sname'+studentname);
               Integer Bname=batch; 
        system.debug('Bname'+batch);
        
        
         

              
}
    
}