public class Opportunity_Object {
//Variable Declaration from Opportunity_Object
Public String opportunityname='Burlington Textiles Weaving Plant Generator';
Public Id accountname='0012w00000MRyYn';
Public String type='New Customer';
Public String leadsource='Web';
Public String ordernumber='645612';
Public String currentgenerator='John Deere';
Public String trackingnumber='830150301360';	
Public String Description;
Public Integer amount=235000;
Public Integer expecterevenue=235000;
Public Date closedate=system.Today();
Public String nextstep;	
Public STring Stage='Closed Won';
Public Integer probability=100;
Public Id primarycampaignsource='7012w000000HkCY';
Public String maincompetitors='John Deere';
Public String deliverystatus='Yet to begin';
}